name: Update Helm Values File
description: Update the image tag in a kustomization directory
inputs:
  github-repo:
    description: The url for the github repo to update
    required: true
  branch-name:
    description: The branch of the github repo to update
    required: false
    default: main
  values-directory:
    description: The path to find the values file
    required: true
  source-branch:
    description: Use the source-branch to determine which values-*.yaml file to use
    required: true
  yaml-path-expression:
    description: The yaml path expression of the value to change
    required: true
  value:
    description: The new value
    required: true
  github-app-id:
    description: The title to be used for a container image label
    required: true
  github-app-key:
    description: The PEM file contents for the GitHub App
    required: true
runs:
  using: composite
  steps:
    - name: Update Helm Values File
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1
      env:
        INPUT_GITHUB_REPO: ${{ inputs.github-repo }}
        INPUT_BRANCH_NAME: ${{ inputs.branch-name }}
        INPUT_VALUES_DIRECTORY: ${{ inputs.values-directory }}
        INPUT_SOURCE_BRANCH: ${{ inputs.source-branch }}
        INPUT_YAML_PATH_EXPRESSION: ${{ inputs.yaml-path-expression }}
        INPUT_VALUE: ${{ inputs.value }}
        INPUT_GITHUB_APP_ID: ${{ inputs.github-app-id }}
        INPUT_GITHUB_APP_KEY: ${{ inputs.github-app-key }}
