name: Update Helm Values File
description: Update the image tag in a kustomization directory
inputs:
  github-repo:
    description: The url for the github repo to update
    required: true
  path:
    description: The path of the values file
    required: true
  yaml-path-expression:
    description: The yaml path expression of the value to change
    required: true
  value:
    description: The new value
    required: true
  github-app-id:
    description: The title to be used for a container image label
    required: true
  github-app-key:
    description: The PEM file contents for the GitHub App
    required: true
runs:
  using: composite
  steps:
    - name: Update Helm Values File
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1
      env:
        INPUT_GITHUB_REPO: ${{ inputs.github-repo }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_YAML_PATH_EXPRESSION: ${{ inputs.yaml-path-expression }}
        INPUT_VALUE: ${{ inputs.value }}
        INPUT_GITHUB_APP_ID: ${{ inputs.github-app-id }}
        INPUT_GITHUB_APP_KEY: ${{ inputs.github-app-key }}
